import type { Metadata } from 'next'
import { Providers } from './providers'
import { Navbar } from './components'
import { getServerSession } from 'next-auth'
import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Landing with auth',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers sessionProps={{ session: session }}>
          <Navbar />
          <main className="mx-auto max-w-7xl min-h-screen p-24">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
