import type { Metadata } from 'next'
import { SectionContainer } from '@/components'

export const metadata: Metadata = {
  title: 'Profile | Landing with Next-Auth',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SectionContainer
      classNames={{
        base: 'min-h-screen dark bg-background/80',
      }}
      justify="center"
    >
      {children}
    </SectionContainer>
  )
}
